server:
  port: 8080
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/im_system?useSSL=false&characterEncoding=UTF8&serverTimezone=UTC&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
